# -*- coding: utf-8 -*-
"""Get_edges_and_nodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8YkglaTcfZ7QC5-1HEMFhe5mQZrMVdf
"""

#pip install osmnx

import osmnx as ox
#import textwrap

def get_data_from_place(place_name):
    """
    Fetch graph data (nodes and edges) for a specified place using osmnx.

    Parameters:
        place_name (str): Name of the place to retrieve the graph data for.

    Returns:
        dict: A dictionary containing nodes and edges data as GeoDataFrames.
            Example structure:
            {
                "edges": GeoDataFrame of edges,
                "nodes": GeoDataFrame of nodes
            }
    """
    try:
        # Retrieve the graph for the given place
        graph = ox.graph_from_place(place_name, network_type='drive')

        # Convert the graph to GeoDataFrames
        nodes, edges = ox.graph_to_gdfs(graph)

        # Create the dictionary object
        dict_object = {
            "nodes": nodes,
            "edges": edges
        }

        return dict_object
    except Exception as e:
        print(f"An error occurred: {e}")
        return None
